name: Trigger Pipeline via Webhook
on:
  repository_dispatch:
    types: [dependency_update]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run pipeline steps
        run: |
          echo "Pipeline triggered by webhook with dependency_update!"
          echo "Version number: ${{ github.event.client_payload.version }}"
          echo "Payload data: ${{ github.event.client_payload.data }}"
          # Add your pipeline steps here (e.g., build, test, deploy)
