name: Trigger Pipeline via Webhook
on:
  repository_dispatch:
    types: [trigger-pipeline]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run pipeline steps
        run: |
          echo "Pipeline triggered by webhook!"
          echo "Payload data: ${{ github.event.client_payload.data }}"
          # Add your pipeline steps here (e.g., build, test, deploy)
      - name: Example step
        run: npm install && npm test
        if: github.event.client_payload.data == 'run-tests'
